### ISSUE TITLE
Configure travis for multi-os support

### ISSUE THREAD

**Issue by mwcraig** [astropy/conda-builder-affiliated#13]
Multi-os is now enabled for this repo on travis.

**Comment by mwcraig** [comment]
This needs intervention by the travis folks for it to work -- see https://travis-ci.org/astropy/conda-builder-affiliated/builds/71587905 which ended up being linux-only even though multi-os is in the `.travis.yml` and the travis folks said multi-os was turned on.

**Comment by astrofrog** [comment]
@mwcraig - done? :)

**Comment by mwcraig** [comment]
Yeah, the travis support person even wrote the PR to do it, too (I had tried same thing yesterday).

Closed by #18
