### ISSUE TITLE
Add instructions on installing packages?

### ISSUE THREAD

**Issue by astrofrog** [astropy/conda-builder-affiliated#19]
It would be nice to add to the README.md instructions for installing packages from this channel (I know this is on binstar, but no harm in listing this here too)

**Comment by mwcraig** [comment]
I'm planning an announcement later today (need to get the latest imexam building on the platforms it can build on, i.e. not windows), including a pointer to shiny badges like this (updating the README here makes sense too, of course): [![Binstar Badge](https://binstar.org/astropy/wcsaxes/badges/installer/conda.svg)](https://conda.binstar.org/astropy)

**Comment by mwcraig** [comment]
These instructions now exist at https://github.com/astropy/conda-channel-astropy and https://github.com/astropy/conda-build-tools
