### ISSUE TITLE
Add pyephem for astroplan

### ISSUE THREAD

**Issue by cdeil** [astropy/conda-builder-affiliated#42]
The astroplan 0.1 release (a new Astropy-affiliated package) is imminent:
https://github.com/astropy/astroplan/issues/21

It would be nice to have a conda package for it soon.
One of it's optional dependencies is `pyephem` for which there is no conda package.

@mwcraig – Can you build one (for `pyephem` for now, not `astroplan` yet) and add it to the astropy channel?

**Comment by mwcraig** [comment]
closed by #45
