### ISSUE TITLE
Add healpy

### ISSUE THREAD

**Issue by cdeil** [astropy/conda-builder-affiliated#48]
As a follow-on to #31, this is a request to add [healpy](https://github.com/healpy/healpy).

healpy is an optional dependency of reproject.

There is https://binstar.org/lsst/lsst-healpy, but I didn't test it so far, and it's Mac / Linux only, no Windows.

I think `healpy` might be quite hard to build / package though...

**Comment by cdeil** [comment]
Having a conda healpy package is now also important for fermipy / @woodmd.
See https://github.com/fermiPy/fermipy/issues/16

@mwcraig - Probably you don't have time and one of us should try and follow the instructions at https://github.com/astropy/conda-builder-affiliated#add-a-new-affiliated-package to build it and once that works make a PR here?

**Comment by mwcraig** [comment]
@cdeil -- actually, as a first step I would try adding it to `requirements.yml` and see what happens. `bdist_conda` is currently sort of broken, it doesn't really bake in the numpy version the way it should if there are numpy compiled extensions. 

It will fail on Windows, but it isn't supported on Windows anyway according to the healpy page.

In addition to the name and version be sure to set `numpy_comlied_extensions: true`.

I won't have time to get healpy working in the short run (several days) but if it builds except for windows can whip up a modification to this builder to exclude platforms in the yml file...right now the only way to exclude platforms is in a recipe template, which is overkill.

**Comment by cdeil** [comment]
@mwcraig - I've tried you suggestion in #93. Can you please have a look?

**Comment by woodmd** [comment]
Is there any status update on this?

**Comment by cdeil** [comment]
Apparently today it was announced that Continuum will move their recipes to https://conda-forge.github.io/ , i.e. getting everything packaged there is the default way forward.

I'm not sure adding healpy to this repo / channel still makes sense.

@mwcraig ?

**Comment by mwcraig** [comment]
I would say for today let's get it building over here: https://github.com/openastronomy/conda-channel

**Comment by mwcraig** [comment]
Give me 10 minutes to hack on the builder-tool....

**Comment by cdeil** [comment]
Closing this issue. 
Discussion should continue on this pull request: https://github.com/OpenAstronomy/conda-channel/pull/3
