### ISSUE TITLE
Build more versions for travis testing

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-builder-affiliated#91]
Would it be feasible in terms of resource requirement, etc to build packages for more versions? My use case would be to use these conda packages rather than pip installing them when they are dependencies of other affiliates. However these packages don't cover the whole version range we usually test.
What usually missing is builds for python 2.6 and 3.3. And if possible python 2.7 builds for older numpies (at least 1.8 and 1.7).

**Comment by mwcraig** [comment]
@bsipocz -- at the moment what would limit this is what numpy/python combinations continuum provides.   The infrastructure for doing it isn't that extensive, though doing it on a per-package basis might be a bit of a hassle (I assume different packages support different minimum versions of python/numpy).

**Comment by bsipocz** [comment]
This is now solved, as `astropy-ci-extras` hosts these combinations.
